OnlineClassroom/routes/web.php
<?php

namespace App\Http\Controllers;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth'])->name('dashboard');

Route :: group(['middleware'=> 'auth'], function(){
    Route::get('/classroom/join', [ClassroomController::class, 'join'])->name('classroom.join');
    Route::post('/classroom/join', [ClassroomController::class, 'add'])->name('classroom.add');
    Route::resource('classroom', ClassroomController::class);
    Route::resource('content', ContentController::class);
    Route::group(['middleware' => 'role:student','prefix' => 'student', 'as' => 'student.'],function(){
        Route ::resource('lessons',\App\Http\Controllers\Students\LessonController::class);
        
    });
Route::group(['middleware' => 'role:teacher','prefix' => 'teacher', 'as' => 'teacher.'],function(){
    Route ::resource('courses',\App\Http\Controllers\Teachers\CourseController::class);
    
});


});

require __DIR__.'/auth.php';

OnlineClassroom/app/Models/Content.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Content extends Model
{
    use HasFactory;
    protected $fillable = [
        'title',
        'description',
    ];

    public function classroom()
    {
        return $this->belongsTo(Classroom::class);
    }
}

OnlineClassroom/app/Http/Controllers/ContentController.php
<?php

namespace App\Http\Controllers;
use App\Models\Classroom;
use Illuminate\Http\Request;
use App\Models\Content;
class ContentController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'title' => 'required|string|max:255',
            'description' => 'required|string|max:255'
        ]);
        
        $do = Classroom::find($request->input('classroom_id'));
        // dd($do->contents);
        $do->contents()->create($request->all());
        return back();
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Content $content)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Content $content)
    {
        return view('content.edit', compact('content'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Content $content)
    {
        $request->validate([
            'title' => 'required|string|max:255',
            'description' => 'required|string|max:255'
        ]);
        $content->update($request->all());
        $classroom = $content->classroom()->first();
        // dd($classroom->id);
        return redirect()->route('classroom.show',$classroom->id);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        
        $content->delete();
        return back();
    }
}

OnlineClassroom/app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

OnlineClassroom/resources/views/content/edit.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Update Content') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-5xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">
                    <form method="POST" action="{{ route('content.update', $content->id) }}">
                        @csrf
                        @method("PATCH")
                        <div>
                            <!-- Class Name -->
                            <div>
                                <x-label for="title" :value="__('Title')" />

                                <x-input id="title" class="block mt-1 w-full" type="text" name="title" :value="$content->title" autofocus />
                            </div>

                           

                            <!-- Description -->
                            <div class="mt-4">
                                <x-label for="description" :value="__('Description')" />

                                <x-input id="description" class="block mt-1 w-full" type="text" name="description" :value="$content->description"/>
                            </div>

                            <div class="flex items-center justify-end mt-4">
                                <x-button class="ml-4">
                                    {{ __('Update content') }}
                                </x-button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</x-app-layout>