OnlineClassroom/routes/web.php
<?php

namespace App\Http\Controllers;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth'])->name('dashboard');

Route :: group(['middleware'=> 'auth'], function(){
    Route::get('/classroom/join', [ClassroomController::class, 'join'])->name('classroom.join');
    Route::post('/classroom/join', [ClassroomController::class, 'add'])->name('classroom.add');
    Route::resource('classroom', ClassroomController::class);
    Route::resource('content', ContentController::class);
    Route::group(['middleware' => 'role:student','prefix' => 'student', 'as' => 'student.'],function(){
        Route ::resource('lessons',\App\Http\Controllers\Students\LessonController::class);
        
    });
Route::group(['middleware' => 'role:teacher','prefix' => 'teacher', 'as' => 'teacher.'],function(){
    Route ::resource('courses',\App\Http\Controllers\Teachers\CourseController::class);
    
});


});

require __DIR__.'/auth.php';

OnlineClassroom/app/Models/Classroom.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Haruncpi\LaravelIdGenerator\IdGenerator;
use Illuminate\Support\Str;
class Classroom extends Model
{
    use HasFactory;
    protected $fillable = [
        'classroom',
        'section',
        'code',
        'description',
        
    ];
    public function users()
    {
        return $this->belongsToMany(User::class);
    }
    public function contents()
    {
        return $this->hasMany(Content::class);
    }

    public static function boot()
    {
        parent::boot();
        self::creating(function ($model) {
            $random = Str::random(4);
            $model->code = IdGenerator::generate(['table'=>'classrooms', 'field'=>'code', 'length' => 10, 'prefix' =>'CLS-']);
            $model->code = $model->code."-".$random;
        });
    }
}

OnlineClassroom/app/Http/Controllers/ClassroomController.php
<?php

namespace App\Http\Controllers;
use App\Models\Classroom;
use Illuminate\Http\Request;
use App\Models\Content;
class ClassroomController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $classrooms = auth()->user()->classrooms()->get();
        return view('classroom.index')->with(['classrooms' => $classrooms]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('classroom.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    
    public function store(Request $request)
    {
        $request->validate([
            'classroom' => 'required|string|max:255',
            'section' => 'required|int|max:255',
            'description' => 'required|string|max:255',
           
        ]);

        auth()->user()->classrooms()->create($request->all());
        return redirect('classroom');

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Classroom $classroom)
    {   
        $contents = $classroom->contents()->orderBy('created_at', 'desc')->get();
        return view('classroom.show', compact('classroom', 'contents')); 
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Classroom $classroom)
    {
        return view('classroom.edit', compact('classroom'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Classroom $classroom)
    {
        $request->validate([
            'classroom' => 'required|string|max:255',
            'section' => 'required|int|max:255',
            'description' => 'required|string|max:255'
        ]);

        $classroom->update($request->all());

        return redirect()->route('classroom.index')
            ->with('success', 'Classroom updated successfully');
        
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Classroom $classroom)
    {
        $classroom->delete();
        return redirect('classroom');
    }
    public function join()
    {
        return view('classroom.join');
    }

    public function add(Request $request)
    {
        $join = Classroom::where('code', $request->input('code'))->get();

        auth()->user()->classrooms()->attach($join->pluck('id'));
        return redirect('classroom');
    }
}

OnlineClassroom/app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

OnlineClassroom/resources/views/classroom/create.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Create New Classroom') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-5xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">
                    <form method="POST" action="{{ route('classroom.store') }}">
                        @csrf
                        <div>
                            <!-- Class Name -->
                            <div>
                                <x-label for="classroom" :value="__('Classroom')" />

                                <x-input id="classroom" class="block mt-1 w-full" type="text" name="classroom" :value="old('classroom')" autofocus />
                            </div>

                            <!-- Section Number -->
                            <div class="mt-4">
                                <x-label for="section" :value="__('Section')" />

                                <x-input id="section" class="block mt-1 w-full" type="number" name="section" :value="old('section')"/>
                            </div>

                            <!-- Description -->
                            <div class="mt-4">
                                <x-label for="description" :value="__('Description')" />

                                <x-input id="description" class="block mt-1 w-full" type="text" name="description" :value="old('description')"/>
                            </div>
                           

                            <div class="flex items-center justify-end mt-4">
                                <x-button class="ml-4">
                                    {{ __('Create New Classroom') }}
                                </x-button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

OnlineClassroom/resources/views/classroom/edit.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ ('Update Classroom') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-5xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">
                    <form method="POST" action="{{ route('classroom.update', $classroom->id) }}">
                        @csrf
                        @method("PATCH")
                        <div>
                            <!-- Class Name -->
                            <div>
                                <x-label for="classroom" :value="('Classroom')" />

                                <x-input id="classroom" class="block mt-1 w-full" type="text" name="classroom" :value="$classroom->classroom" autofocus />
                            </div>
                            <!-- Section Number -->
                            <div class="mt-4">
                                <x-label for="section" :value="('Section')" />

                                <x-input id="section" class="block mt-1 w-full" type="number" name="section" :value="$classroom->section"/>
                            </div>

                            <!-- Description -->
                            <div class="mt-4">
                                <x-label for="description" :value="('Description')" />

                                <x-input id="description" class="block mt-1 w-full" type="text" name="description" :value="$classroom->description"/>
                            </div>

                            <div class="flex items-center justify-end mt-4">
                                <x-button class="ml-4">
                                    {{ __('Update Classroom') }}
                                </x-button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

OnlineClassroom/resources/views/classroom/index.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('All Classroom') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="grid grid-cols-3 gap-4">
            @foreach ($classrooms as $classroom)
                <div class="bg-white overflow-hidden shadow-sm sm:rounded-sm">
                    <div class="bg-white border-b border-gray-200">
                        <div class="bg-red-400 p-6">
                            <div class="flex justify-between">
                                <a href="classroom/{{$classroom->id}}" class="font-bold text-gray-50 text-lg capitalize">
                                    {{$classroom->classroom}}
                                </a>

                                <div class="flex">
                                    @can('delete-classroom', User::class)
                                    <form action="{{ route('classroom.destroy', $classroom->id)}}" method="POST">
                                        @csrf
                                        @method("DELETE")
                                        <button type="submit">
                                            <x-icons.delete/>
                                        </button>
                                    </form>
                                    @endcan
    
                                    @can('update-classroom', User::class)
                                    <a href="{{ route('classroom.edit', $classroom->id)}}">
                                        <x-icons.update/>
                                    </a>
                                    @endcan
                                </div>
                    
                            </div>

                            <p class="text-gray-100 text-sm">{{$classroom->section}}</p>
                        </div>
                        <div class="p-6">
                            <ul>
                                <h5 class="font-bold">Upcoming Tasks:</h5>
                                <li>Final Assignment</li>
                            </ul>
                        </div>
                    </div>
                </div>
            @endforeach
            </div>
        </div>
    </div>

</x-app-layout>

OnlineClassroom/resources/views/classroom/join.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ ('Create New Classroom') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-5xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">
                    <form method="POST" action="{{ route('classroom.join') }}">
                        @csrf
                        <div>
                            <!-- Class Name -->
                            <div>
                                <x-label for="code" :value="('code')" />

                                <x-input id="code" class="block mt-1 w-full" type="text" name="code" :value="old('code')" autofocus />
                            </div>


                            <div class="flex items-center justify-end mt-4">
                                <x-button class="ml-4">
                                    {{ __('Join New Classroom') }}
                                </x-button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

OnlineClassroom/resources/views/classroom/show.blade.php
<x-app-layout>
    <div class="container relative d-flex mx-auto p-10 h-60 bg-blue-400 shadow items-baseline rounded">
        <h2 class="text-blue-100 font-black text-5xl mb-1">{{$classroom->classroom}}</h2>
        <h4 class="text-white text-lg mb-10"><span>Section: </span>{{$classroom->section}}</h4>
        <h4 class="text-white text-2xl">{{$classroom->description}}</h4>
        <h4 class="text-white text-2xl"><span class="fw-bold">Class Code: </span>{{$classroom->code}}</h4>
    </div>


    <div class="container mx-auto mt-10">
        <div class="grid grid-cols-6 gap-4">
            <div class="col-start-2 col-span-4 shadow-sm bg-white p-10 mb-5">

                <form method="POST" action="{{ route('content.store') }}">
                    @csrf
                    <div>
                        <h1 class="font-bold mb-10 text-3xl">Create a New Post:</h1>
                        <!-- Class Name -->
                        <div>
                            <x-label for="title" :value="__('Title')" />
                            <x-input id="title" class="block mt-1 w-full" type="text" name="title" :value="old('title')"
                                autofocus />
                        </div>

                        <!-- Section Number -->
                        <div class="mt-4">
                            <x-label class="mt-5" for="description" :value="__('Description')" />
                            <textarea name="description" id="description" class="block mt-1 w-full rounded-md shadow-sm border-gray-300 focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50"></textarea>
                        </div>

                        <input type="hidden" value="{{$classroom->id}}" name="classroom_id">

                        <div class="flex items-center justify-end mt-4">
                            <x-button class="ml-4">
                                {{ __('post') }}
                            </x-button>
                        </div>
                    </div>
                </form>
            </div>
            @foreach ($contents as $content)
            <div class="relative col-start-2 col-span-4 shadow-lg bg-white p-5">

                <div x-data="{ show: false }" class="absolute top-0 right-0 mt-5 mr-5">
                    <div class="hidden sm:flex sm:items-center sm:ml-6">
                        <x-dropdown align="right" width="48">
                            <x-slot name="trigger">
                                <button class="flex items-center text-sm font-medium text-gray-500 hover:text-gray-700 hover:border-gray-300 focus:outline-none focus:text-gray-700 focus:border-gray-300 transition duration-150 ease-in-out">        
                                    <div class="ml-1">
                                        <x-icons.more-vert/>
                                    </div>
                                </button>
                            </x-slot>
        
                            <x-slot name="content">
                               <x-dropdown-link href="{{ route('content.edit', $content->id)}}">
                                    {{ __('Update') }}
                                </x-dropdown-link>
                                <x-dropdown-link>
                                <form action="{{ route('content.destroy', $content->id)}}" method="POST">
                                        @csrf
                                        @method("DELETE")
                                        <button type="submit">
                                        {{ __('Delete') }}
                                        </button>
                                    </form>
                                    </x-dropdown-link>
                            </x-slot>
                        </x-dropdown>
                    </div>
                </div>

                <h2 class="font-bold text-lg">{{$content->title}}</h2>    
                <p class="text-xs">Updated at: {{$content->updated_at}}</p>    
                <p class="mt-5 text-lg">{{$content->description}}</p>    
            </div>
            @endforeach
        </div>
    </div>
</x-app-layout>